version: 2

jobs:
  test:
    docker:
      - image: node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies and check lint
          command: |
            npm install
            npm run lint
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build:
    docker:
      - image: node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies and build
          command: |
            # Should sed release version here
            npm install
            npm run build:ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  sentry:
    docker:
      - image: getsentry/sentry-cli
    working_directory: ~/repo
    steps:
      - run:
          name: Install git and ssh
          command: apk add --no-cache git openssh-client
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: ~/repo
      - run:
          name: Upload to sentry
          command: |
            sentry-cli releases new $CIRCLE_SHA1
            sentry-cli releases set-commits --auto $CIRCLE_SHA1
            sentry-cli releases files $CIRCLE_SHA1 upload-sourcemaps ./dist \
              -x .js -x .map \
              --validate \
              --verbose \
              --rewrite \
              --strip-common-prefix
            sentry-cli releases finalize $CIRCLE_SHA1

  deploy:
    docker:
      - image: node:12.14
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "arthurc0102@gmail.com"
            git config user.name "Arthur Chang"
      - add_ssh_keys:
          fingerprints:
            - "93:dc:66:67:d6:19:51:c0:82:33:4f:4d:93:98:44:fd"
      - run:
          name: Deploy to gh-pages branch
          command: |
            rm -rfv dist/{**/,}*.map
            gh-pages --dist dist --message "[skip ci] Updates $CIRCLE_SHA1" --no-history

workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - sentry:
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
            - build
            - sentry
          filters:
            branches:
              only:
                - master
